services:
    _defaults:
        autoconfigure: true

    Clickpress\Update\Controller\FrontendApiController:
        tags:
            - "terminal42_service_annotation"
            - "controller.service_arguments"
        calls:
            - [setContainer, ["@service_container"]]
        public: true
